name: project03

services:
  db:
    image: mysql:9.0.1
    container_name: project03
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Project03
      MYSQL_USER: passie
      MYSQL_PASSWORD: root
    ports:
      - "8080:3306"
    volumes:
      - db-data:/var/lib/mysql
    
volumes:
  db-data: